### ISSUE TITLE
Uncaught errors in Vehicle endpoint

### ISSUE THREAD

**Issue by Bertware** [iRail/iRail#379]
```
PHP Fatal error:  Uncaught Error: Call to a member function getElementByTagName() on null in /var/www/api.irail.be/api/data/NMBS/vehicleinformation.php:139"
 "Stack trace:"
"#0 /var/www/api.irail.be/api/data/NMBS/vehicleinformation.php(66): vehicleinformation::getData(Object(simple_html_dom), 'EN', 'false', Array, '110419', 'BE.NMBS.S11995', NULL)"
"#1 /var/www/api.irail.be/api/data/DataRoot.php(68): vehicleinformation::fillDataRoot(Object(DataRoot), Object(VehicleinformationRequest))"
"#2 /var/www/api.irail.be/api/APICall.php(84): DataRoot->fetchData(Object(VehicleinformationRequest))"
"#3 /var/www/api.irail.be/api/vehicle.php(11): APICall->executeCall()"
"#4 {main}"
"  thrown in /var/www/api.irail.be/api/data/NMBS/vehicleinformation.php on line 139"
```

```
PHP Fatal error:  Uncaught Error: Call to a member function format() on boolean in /var/www/api.irail.be/api/data/NMBS/vehicleinformation.php:100
Stack trace:
#0 /var/www/api.irail.be/api/data/NMBS/vehicleinformation.php(31): vehicleinformation::getServerData('P1234', '', 'EN')
#1 /var/www/api.irail.be/api/data/DataRoot.php(68): vehicleinformation::fillDataRoot(Object(DataRoot), Object(VehicleinformationRequest))
#2 /var/www/api.irail.be/api/APICall.php(84): DataRoot->fetchData(Object(VehicleinformationRequest))
#3 /var/www/api.irail.be/api/vehicle.php(11): APICall->executeCall()
#4 {main}
  thrown in /var/www/api.irail.be/api/data/NMBS/vehicleinformation.php on line 100

```

**Comment by Bertware** [comment]
Fix this by fixing #332
