### ISSUE TITLE
/liveboard for Brussel-Zuid has error 502

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#438]
For some reason Brussel-Zuid gives and error 502 now: https://api.irail.be/liveboard/?station=brussel-zuid

Other stations seem to be fine. 

(I’m on the go, so can’t check with actual station ID, but Railer also gives an error.)

![8A13E441-0B1D-4B31-9616-BC6D58C7DA78](https://user-images.githubusercontent.com/995815/110211267-296aee80-7e96-11eb-8d7b-3492a4a5755f.png)

**Comment by Bertware** [comment]
2 possible causes:
```
PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Irail\api\data\NMBS\tools\HafasCommon::throwExceptionOnInvalidResponse() must be of the type array, null given, called in /var/www/api.irail.be/src/api/data/NMBS/LiveboardDatasource.php on line 242 and defined in /var/www/api.irail.be/src/api/data/NMBS/tools/HafasCommon.php:23
Stack trace:
#0 /var/www/api.irail.be/src/api/data/NMBS/LiveboardDatasource.php(242): Irail\api\data\NMBS\tools\HafasCommon::throwExceptionOnInvalidResponse(NULL)
#1 /var/www/api.irail.be/src/api/data/NMBS/LiveboardDatasource.php(116): Irail\api\data\NMBS\LiveboardDatasource::parseNmbsData('', 'EN')
#2 /var/www/api.irail.be/src/api/data/NMBS/LiveboardDatasource.php(44): Irail\api\data\NMBS\LiveboardDatasource::FillDataRootWithDepartureData(Object(Irail\api\data\DataRoot), Object(Irail\api\requests\LiveboardRequest))
#3 /var/www/api.irail.be/src/api/data/DataRoot.php(82): Irail\api\data\NMBS\LiveboardDatasource::fillDataRoot(Object(Irail\api\data\DataRoot), Objec" while reading response header from upstream, client: 195.238.25.37, server: api.irail.be, request: "GET /liveboard/?station=BE.NMBS.008863008&format=json&fast=true HTTP/2.0", upstream: "fastcgi://127.0.0.1:9100", host: "api.irail.be"
```

`Could not get data: Could not match 'Rennes' with a station id in iRail.`

Weird that the error isn't displayed, php errors should never cause a bad gateway error in our setup. Will fix
