### ISSUE TITLE
Issues on staging

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#520]
Currently staging is acting up quite a bit (‼️ not happening on production):

- [ ] Sometimes, the connection endpoint only returns the first trains of the day (e.g. at 5:30 am), even when no date parameter is set. When setting a date parameter, no results are returned. Unfortunately I don't know how to reproduce it. 

- [ ] Every few minutes I get an `Error 504` on the connections endpoint (no other info given). e.g. https://staging.api.irail.be/connections/?lang=nl&format=json&from=BE.NMBS.008814001&to=BE.NMBS.008891702&timesel=departure
<img width="1177" alt="image" src="https://github.com/iRail/iRail/assets/995815/63dec13e-0973-4e77-9fc9-7d6accb6588e">

- [ ] Some vehicles give the same error as above: https://staging.api.irail.be/vehicle/?lang=nl&id=BE.NMBS.S425487&alerts=true&date=060524

- [ ] Liveboard endpoint not always working: https://staging.api.irail.be/v1/liveboard/?lang=nl&station=BE.NMBS.008844628
```
{"code":0,"request-id":"9bf856b0-87dd-4909-bb67-5442303cff5e","message":"Too few arguments to function Irail\\Repositories\\Nmbs\\NmbsRivLiveboardRepository::__construct(), 3 passed in \/workspace\/app\/Repositories\/Nmbs\/NmbsMergedLiveboardRepository.php on line 25 and exactly 4 expected","previous":null,"at":"\/workspace\/app\/Repositories\/Nmbs\/NmbsMergedLiveboardRepository.php:25","stack":["#0 \/workspace\/app\/Repositories\/Nmbs\/NmbsMergedLiveboardRepository.php(25): Irail\\Repositories\\Nmbs\\NmbsRivLiveboardRepository->__construct(Object(Irail\\Repositories\\Irail\\StationsRepository), Object(Irail\\Repositories\\Gtfs\\GtfsTripStartEndExtractor), Object(Irail\\Repositories\\Riv\\NmbsRivRawDataRepository))","#1 \/workspace\/app\/Http\/Controllers\/LiveboardV1Controller.php(31): Irail\\Repositories\\Nmbs\\NmbsMergedLiveboardRepository->getLiveboard(Object(Irail\\Http\\Requests\\LiveboardV1Request))","#2 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(36): Irail\\Http\\Controllers\\LiveboardV1Controller->getLiveboardById(Object(Irail\\Http\\Requests\\LiveboardV1Request), '')","#3 \/workspace\/vendor\/illuminate\/container\/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()","#4 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))","#5 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))","#6 \/workspace\/vendor\/illuminate\/container\/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)","#7 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(391): Illuminate\\Container\\Container->call(Array, Array)","#8 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(356): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)","#9 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(331): Laravel\\Lumen\\Application->callLumenController(Object(Irail\\Http\\Controllers\\LiveboardV1Controller), 'getLiveboardByI...', Array)","#10 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(284): Laravel\\Lumen\\Application->callControllerAction(Array)","#11 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(269): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)","#12 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(239): Laravel\\Lumen\\Application->handleFoundRoute(Array)","#13 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(174): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)","#14 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(48): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#15 \/workspace\/app\/Http\/Middleware\/RequestLoggingMiddleware.php(28): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#16 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Irail\\Http\\Middleware\\RequestLoggingMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#17 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#18 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(59): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#19 \/workspace\/vendor\/illuminate\/cache\/RateLimiter.php(78): Irail\\Http\\Middleware\\RateLimitMiddleware->Irail\\Http\\Middleware\\{closure}()","#20 \/workspace\/vendor\/illuminate\/support\/Facades\/Facade.php(355): Illuminate\\Cache\\RateLimiter->attempt('request_rate|bu...', 12, Object(Closure), 5)","#21 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(55): Illuminate\\Support\\Facades\\Facade::__callStatic('attempt', Array)","#22 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(37): Irail\\Http\\Middleware\\RateLimitMiddleware->rateLimitedShortTerm(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#23 \/workspace\/vendor\/illuminate\/cache\/RateLimiter.php(78): Irail\\Http\\Middleware\\RateLimitMiddleware->Irail\\Http\\Middleware\\{closure}()","#24 \/workspace\/vendor\/illuminate\/support\/Facades\/Facade.php(355): Illuminate\\Cache\\RateLimiter->attempt('request_rate|lo...', 1800, Object(Closure), 3600)","#25 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(33): Illuminate\\Support\\Facades\\Facade::__callStatic('attempt', Array)","#26 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(23): Irail\\Http\\Middleware\\RateLimitMiddleware->rateLimitedLongTerm(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#27 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Irail\\Http\\Middleware\\RateLimitMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#28 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#29 \/workspace\/vendor\/illuminate\/http\/Middleware\/TrustProxies.php(39): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#30 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#31 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#32 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(119): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#33 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(428): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#34 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(167): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#35 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(112): Laravel\\Lumen\\Application->dispatch(NULL)","#36 \/workspace\/public\/index.php(28): Laravel\\Lumen\\Application->run()","#37 {main}"]}
```

**Comment by Bertware** [comment]
Before the deployment of the new production code, staging was used for some performance testing (seeing how many days could be loaded on the small instance). This caused instability due to RAM running out, leading to the issues as in your screenshot. I've now reduced the number of days to load GTFS for to 14, meaning you can only search two weeks in the future. This should reduce the load on the server instance, while still being sufficient for testing. 

Regarding the other issues, I'm still iterating quite fast on the new codebase, which lead to the development branch currently running an unstable build. This should be fixed within a couple of days

**Comment by jncn** [comment]
Great! Thanks for the clarification ❤️ Keep it up!
