### ISSUE TITLE
Some connections give an error when lang=de

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#523]
Happens on staging and production.

e.g. https://api.irail.be/v1/connections/?lang=de&to=BE.NMBS.008872009&from=BE.NMBS.008833001

```
{"code":0,"request-id":"9c09348e-de6f-4751-a35f-42dae66cd099","message":"Call to a member function getLocalizedStationName() on null","previous":null,"at":"\/workspace\/app\/Http\/Responses\/v1\/JourneyPlanningV1Converter.php:68","stack":["#0 \/workspace\/app\/Http\/Responses\/v1\/JourneyPlanningV1Converter.php(68): Irail\\Http\\Responses\\v1\\JourneyPlanningV1Converter::convertDirection(Object(Irail\\Models\\DepartureOrArrival))","#1 \/workspace\/app\/Http\/Responses\/v1\/JourneyPlanningV1Converter.php(38): Irail\\Http\\Responses\\v1\\JourneyPlanningV1Converter::convertDeparture(Object(Irail\\Models\\DepartureOrArrival), Object(Irail\\Models\\JourneyLeg))","#2 \/workspace\/app\/Http\/Responses\/v1\/JourneyPlanningV1Converter.php(31): Irail\\Http\\Responses\\v1\\JourneyPlanningV1Converter::convertJourneyPlan(Object(Irail\\Models\\Journey))","#3 [internal function]: Irail\\Http\\Responses\\v1\\JourneyPlanningV1Converter::Irail\\Http\\Responses\\v1\\{closure}(Object(Irail\\Models\\Journey))","#4 \/workspace\/app\/Http\/Responses\/v1\/JourneyPlanningV1Converter.php(31): array_map(Object(Closure), Array)","#5 \/workspace\/app\/Http\/Controllers\/JourneyPlanningV1Controller.php(37): Irail\\Http\\Responses\\v1\\JourneyPlanningV1Converter::convert(Object(Irail\\Http\\Requests\\JourneyPlanningV1RequestImpl), Object(Irail\\Models\\Result\\JourneyPlanningSearchResult))","#6 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(36): Irail\\Http\\Controllers\\JourneyPlanningV1Controller->getJourneyPlanning(Object(Irail\\Http\\Requests\\JourneyPlanningV1RequestImpl), '')","#7 \/workspace\/vendor\/illuminate\/container\/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()","#8 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))","#9 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))","#10 \/workspace\/vendor\/illuminate\/container\/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)","#11 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(391): Illuminate\\Container\\Container->call(Array, Array)","#12 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(356): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)","#13 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(331): Laravel\\Lumen\\Application->callLumenController(Object(Irail\\Http\\Controllers\\JourneyPlanningV1Controller), 'getJourneyPlann...', Array)","#14 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(284): Laravel\\Lumen\\Application->callControllerAction(Array)","#15 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(269): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)","#16 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(239): Laravel\\Lumen\\Application->handleFoundRoute(Array)","#17 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(174): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)","#18 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(48): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#19 \/workspace\/app\/Http\/Middleware\/RequestLoggingMiddleware.php(28): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#20 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Irail\\Http\\Middleware\\RequestLoggingMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#21 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#22 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(59): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#23 \/workspace\/vendor\/illuminate\/cache\/RateLimiter.php(78): Irail\\Http\\Middleware\\RateLimitMiddleware->Irail\\Http\\Middleware\\{closure}()","#24 \/workspace\/vendor\/illuminate\/support\/Facades\/Facade.php(355): Illuminate\\Cache\\RateLimiter->attempt('request_rate|bu...', 12, Object(Closure), 5)","#25 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(55): Illuminate\\Support\\Facades\\Facade::__callStatic('attempt', Array)","#26 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(37): Irail\\Http\\Middleware\\RateLimitMiddleware->rateLimitedShortTerm(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#27 \/workspace\/vendor\/illuminate\/cache\/RateLimiter.php(78): Irail\\Http\\Middleware\\RateLimitMiddleware->Irail\\Http\\Middleware\\{closure}()","#28 \/workspace\/vendor\/illuminate\/support\/Facades\/Facade.php(355): Illuminate\\Cache\\RateLimiter->attempt('request_rate|lo...', 1800, Object(Closure), 3600)","#29 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(33): Illuminate\\Support\\Facades\\Facade::__callStatic('attempt', Array)","#30 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(23): Irail\\Http\\Middleware\\RateLimitMiddleware->rateLimitedLongTerm(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#31 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Irail\\Http\\Middleware\\RateLimitMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#32 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#33 \/workspace\/vendor\/illuminate\/http\/Middleware\/TrustProxies.php(39): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#34 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#35 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#36 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(119): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#37 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(428): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#38 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(167): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#39 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(112): Laravel\\Lumen\\Application->dispatch(NULL)","#40 \/workspace\/public\/index.php(28): Laravel\\Lumen\\Application->run()","#41 {main}"]}
```

**Comment by Bertware** [comment]
I was able to reproduce the issue and added a capture of the back-end data to the development branch, but haven't been able to reproduce and test yet, will likely fix one of the coming days
