### ISSUE TITLE
Service alerts gives an error

### ISSUE THREAD

**Issue by VandeVoordeMatthias** [iRail/iRail#525]
Hi, currently the endpoint `/v2/servicealerts` gives an error. The v1 is working fine.

Request:
`https://api.irail.be/v2/servicealerts`

Response:
```json
{
  "code": 0,
  "request-id": "9c0c2e2e-6d7d-4f10-9dbb-0ae1b5dcb83b",
  "message": "Irail\\Http\\Responses\\v2\\V2Converter::convertDateTime(): Argument #1 ($dateTime) must be of type Carbon\\Carbon, null given, called in /workspace/app/Http/Responses/v2/V2Converter.php on line 106",
  "previous": null,
  "at": "/workspace/app/Http/Responses/v2/V2Converter.php:106",
  "stack": [
    "#0 /workspace/app/Http/Responses/v2/V2Converter.php(106): Irail\\Http\\Responses\\v2\\V2Converter::convertDateTime(NULL)",
    "#1 /workspace/app/Http/Responses/v2/ServiceAlertsV2Converter.php(21): Irail\\Http\\Responses\\v2\\V2Converter::convertMessage(Object(Irail\\Models\\Message))",
    "#2 [internal function]: Irail\\Http\\Responses\\v2\\ServiceAlertsV2Converter::Irail\\Http\\Responses\\v2\\{closure}(Object(Irail\\Models\\Message))",
    "#3 /workspace/app/Http/Responses/v2/ServiceAlertsV2Converter.php(21): array_map(Object(Closure), Array)",
    "#4 /workspace/app/Http/Controllers/ServiceAlertsV2Controller.php(28): Irail\\Http\\Responses\\v2\\ServiceAlertsV2Converter::convert(Object(Irail\\Http\\Requests\\ServiceAlertsV2Request), Object(Irail\\Models\\Result\\ServiceAlertsResult))",
    "#5 /workspace/vendor/illuminate/container/BoundMethod.php(36): Irail\\Http\\Controllers\\ServiceAlertsV2Controller->getServiceAlerts(Object(Irail\\Http\\Requests\\ServiceAlertsV2Request))",
    "#6 /workspace/vendor/illuminate/container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()",
    "#7 /workspace/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))",
    "#8 /workspace/vendor/illuminate/container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))",
    "#9 /workspace/vendor/illuminate/container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)",
    "#10 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(391): Illuminate\\Container\\Container->call(Array, Array)",
    "#11 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(356): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)",
    "#12 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(331): Laravel\\Lumen\\Application->callLumenController(Object(Irail\\Http\\Controllers\\ServiceAlertsV2Controller), 'getServiceAlert...', Array)",
    "#13 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(284): Laravel\\Lumen\\Application->callControllerAction(Array)",
    "#14 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(269): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)",
    "#15 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(171): Laravel\\Lumen\\Application->handleFoundRoute(Array)",
    "#16 /workspace/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(48): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#17 /workspace/app/Http/Middleware/RequestLoggingMiddleware.php(28): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#18 /workspace/vendor/illuminate/pipeline/Pipeline.php(183): Irail\\Http\\Middleware\\RequestLoggingMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))",
    "#19 /workspace/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#20 /workspace/app/Http/Middleware/RateLimitMiddleware.php(59): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#21 /workspace/vendor/illuminate/cache/RateLimiter.php(78): Irail\\Http\\Middleware\\RateLimitMiddleware->Irail\\Http\\Middleware\\{closure}()",
    "#22 /workspace/vendor/illuminate/support/Facades/Facade.php(355): Illuminate\\Cache\\RateLimiter->attempt('request_rate|bu...', 12, Object(Closure), 5)",
    "#23 /workspace/app/Http/Middleware/RateLimitMiddleware.php(55): Illuminate\\Support\\Facades\\Facade::__callStatic('attempt', Array)",
    "#24 /workspace/app/Http/Middleware/RateLimitMiddleware.php(37): Irail\\Http\\Middleware\\RateLimitMiddleware->rateLimitedShortTerm(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))",
    "#25 /workspace/vendor/illuminate/cache/RateLimiter.php(78): Irail\\Http\\Middleware\\RateLimitMiddleware->Irail\\Http\\Middleware\\{closure}()",
    "#26 /workspace/vendor/illuminate/support/Facades/Facade.php(355): Illuminate\\Cache\\RateLimiter->attempt('request_rate|lo...', 1800, Object(Closure), 3600)",
    "#27 /workspace/app/Http/Middleware/RateLimitMiddleware.php(33): Illuminate\\Support\\Facades\\Facade::__callStatic('attempt', Array)",
    "#28 /workspace/app/Http/Middleware/RateLimitMiddleware.php(23): Irail\\Http\\Middleware\\RateLimitMiddleware->rateLimitedLongTerm(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))",
    "#29 /workspace/vendor/illuminate/pipeline/Pipeline.php(183): Irail\\Http\\Middleware\\RateLimitMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))",
    "#30 /workspace/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#31 /workspace/vendor/illuminate/http/Middleware/TrustProxies.php(39): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#32 /workspace/vendor/illuminate/pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))",
    "#33 /workspace/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#34 /workspace/vendor/illuminate/pipeline/Pipeline.php(119): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#35 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(428): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
    "#36 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(167): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))",
    "#37 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(112): Laravel\\Lumen\\Application->dispatch(NULL)",
    "#38 /workspace/public/index.php(28): Laravel\\Lumen\\Application->run()",
    "#39 {main}"
  ]
}
```

**Comment by Bertware** [comment]
The /v2 endpoints are drafts which are not final yet, and some have broken while refactoring or fixing certain features in the v1 endpoints. Once v2 endpoints are defined and in production they should work correctly, right now focus is on getting correct responses in all cases
