### ISSUE TITLE
Connections show wrong departure times or error

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#528]
When there's no time set, many departure times are wrong:
https://api.irail.be/connections/?lang=nl&to=BE.NMBS.008891702&from=BE.NMBS.008833001
https://api.irail.be/connections/?lang=nl&to=BE.NMBS.008813003&from=BE.NMBS.008833001
https://api.irail.be/connections/?lang=nl&to=BE.NMBS.008833001&from=BE.NMBS.008813003

|  |  |  |
| --- | --- | --- |
| ![Simulator Screenshot - iPhone 15 Pro - 2024-06-12 at 08 33 37](https://github.com/iRail/iRail/assets/995815/5e505f3e-0455-4d33-b907-886b768378c6) | ![Simulator Screenshot - iPhone 15 Pro - 2024-06-12 at 08 34 17](https://github.com/iRail/iRail/assets/995815/e40810b1-e1d0-4ecd-a636-a4a89ecc2d2c) | ![Simulator Screenshot - iPhone 15 Pro - 2024-06-12 at 08 34 22](https://github.com/iRail/iRail/assets/995815/4b757339-94eb-48da-8835-79b93d8fee2d) |

Error:
https://api.irail.be/v1/connections/?lang=nl&to=BE.NMBS.008844628&from=BE.NMBS.008814001
https://api.irail.be/connections/?lang=nl&to=BE.NMBS.008872009&from=BE.NMBS.008833001
```
{"code":0,"request-id":"9c445cde-7a0e-4941-89e2-005694646f92","message":"Typed property Irail\\Http\\Requests\\JourneyPlanningV1RequestImpl::$timeSelection must not be accessed before initialization","previous":null,"at":"\/workspace\/app\/Http\/Requests\/JourneyPlanningCacheId.php:15","stack":["#0 \/workspace\/app\/Http\/Requests\/JourneyPlanningCacheId.php(15): Irail\\Http\\Requests\\JourneyPlanningV1RequestImpl->getTimeSelection()","#1 \/workspace\/app\/Repositories\/Riv\/NmbsRivRawDataRepository.php(92): Irail\\Http\\Requests\\JourneyPlanningV1RequestImpl->getCacheId()","#2 \/workspace\/app\/Repositories\/Nmbs\/NmbsRivJourneyPlanningRepository.php(91): Irail\\Repositories\\Riv\\NmbsRivRawDataRepository->getRoutePlanningData(Object(Irail\\Http\\Requests\\JourneyPlanningV1RequestImpl))","#3 \/workspace\/app\/Http\/Controllers\/JourneyPlanningV1Controller.php(36): Irail\\Repositories\\Nmbs\\NmbsRivJourneyPlanningRepository->getJourneyPlanning(Object(Irail\\Http\\Requests\\JourneyPlanningV1RequestImpl))","#4 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(36): Irail\\Http\\Controllers\\JourneyPlanningV1Controller->getJourneyPlanning(Object(Irail\\Http\\Requests\\JourneyPlanningV1RequestImpl), '')","#5 \/workspace\/vendor\/illuminate\/container\/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()","#6 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))","#7 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))","#8 \/workspace\/vendor\/illuminate\/container\/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)","#9 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(391): Illuminate\\Container\\Container->call(Array, Array)","#10 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(356): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)","#11 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(331): Laravel\\Lumen\\Application->callLumenController(Object(Irail\\Http\\Controllers\\JourneyPlanningV1Controller), 'getJourneyPlann...', Array)","#12 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(284): Laravel\\Lumen\\Application->callControllerAction(Array)","#13 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(269): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)","#14 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(239): Laravel\\Lumen\\Application->handleFoundRoute(Array)","#15 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(174): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)","#16 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(48): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#17 \/workspace\/app\/Http\/Middleware\/RequestLoggingMiddleware.php(28): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#18 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Irail\\Http\\Middleware\\RequestLoggingMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#19 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#20 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(59): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#21 \/workspace\/vendor\/illuminate\/cache\/RateLimiter.php(78): Irail\\Http\\Middleware\\RateLimitMiddleware->Irail\\Http\\Middleware\\{closure}()","#22 \/workspace\/vendor\/illuminate\/support\/Facades\/Facade.php(355): Illuminate\\Cache\\RateLimiter->attempt('request_rate|bu...', 12, Object(Closure), 5)","#23 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(55): Illuminate\\Support\\Facades\\Facade::__callStatic('attempt', Array)","#24 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(37): Irail\\Http\\Middleware\\RateLimitMiddleware->rateLimitedShortTerm(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#25 \/workspace\/vendor\/illuminate\/cache\/RateLimiter.php(78): Irail\\Http\\Middleware\\RateLimitMiddleware->Irail\\Http\\Middleware\\{closure}()","#26 \/workspace\/vendor\/illuminate\/support\/Facades\/Facade.php(355): Illuminate\\Cache\\RateLimiter->attempt('request_rate|lo...', 1800, Object(Closure), 3600)","#27 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(33): Illuminate\\Support\\Facades\\Facade::__callStatic('attempt', Array)","#28 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(23): Irail\\Http\\Middleware\\RateLimitMiddleware->rateLimitedLongTerm(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#29 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Irail\\Http\\Middleware\\RateLimitMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#30 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#31 \/workspace\/vendor\/illuminate\/http\/Middleware\/TrustProxies.php(39): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#32 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#33 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#34 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(119): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#35 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(428): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#36 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(167): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#37 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(112): Laravel\\Lumen\\Application->dispatch(NULL)","#38 \/workspace\/public\/index.php(28): Laravel\\Lumen\\Application->run()","#39 {main}"]}
```

Some are correct though:
https://api.irail.be/connections/?lang=nl&to=BE.NMBS.008833001&from=BE.NMBS.008891702

|  |  |  |
| --- | --- | --- |
| ![Simulator Screenshot - iPhone 15 Pro - 2024-06-12 at 08 34 03](https://github.com/iRail/iRail/assets/995815/4724c8c7-053a-454d-a5a0-0c356a86b298) | | |

**Comment by Bertware** [comment]
My bad, didn't properly test all cases when quickly fixing another issue with timeSel yesterday, which caused the default value to no longer be set. Should be fixed within a couple of minutes.

**Comment by jncn** [comment]
No worries! Thanks for the quick reverse 👍
