### ISSUE TITLE
Antwerpen-Berchem Liveboard API broken

### ISSUE THREAD

**Issue by hansottowirtz** [iRail/iRail#533]
Not sure if something changed, but this URL is broken: https://api.irail.be/v1/liveboard?station=Antwerpen-Berchem&format=json

```json
{
  "code": 0,
  "request-id": "9ceb51c0-2f28-4ff0-8e7b-49fb66631073",
  "message": "Undefined array key 8821006",
  "previous": null,
  "at": "/workspace/app/Repositories/Gtfs/GtfsTripStartEndExtractor.php:124",
  "stack": [
    "#0 /workspace/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php(47): Laravel\\Lumen\\Application->handleError(2, 'Undefined array...', '/workspace/app/...', 124)",
    "#1 /workspace/app/Repositories/Gtfs/GtfsTripStartEndExtractor.php(124): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(2, 'Undefined array...', '/workspace/app/...', 124)",
    "#2 /workspace/app/Traits/Cache.php(188): Irail\\Repositories\\Gtfs\\GtfsTripStartEndExtractor->Irail\\Repositories\\Gtfs\\{closure}()",
    "#3 /workspace/app/Repositories/Gtfs/GtfsTripStartEndExtractor.php(81): Irail\\Repositories\\Gtfs\\GtfsTripStartEndExtractor->getCacheOrUpdate('getVehicleWithO...', Object(Closure), 84137)",
    "#4 /workspace/app/Repositories/Gtfs/GtfsTripStartEndExtractor.php(49): Irail\\Repositories\\Gtfs\\GtfsTripStartEndExtractor->getVehicleWithOriginAndDestination('729', Object(Carbon\\Carbon))",
    "#5 /workspace/app/Traits/Cache.php(188): Irail\\Repositories\\Gtfs\\GtfsTripStartEndExtractor->Irail\\Repositories\\Gtfs\\{closure}()",
    "#6 /workspace/app/Repositories/Gtfs/GtfsTripStartEndExtractor.php(43): Irail\\Repositories\\Gtfs\\GtfsTripStartEndExtractor->getCacheOrUpdate('getStartDate|72...', Object(Closure), 84156)",
    "#7 /workspace/app/Repositories/Nmbs/NmbsRivLiveboardRepository.php(153): Irail\\Repositories\\Gtfs\\GtfsTripStartEndExtractor->getStartDate(729, Object(Carbon\\Carbon))",
    "#8 /workspace/app/Repositories/Nmbs/NmbsRivLiveboardRepository.php(88): Irail\\Repositories\\Nmbs\\NmbsRivLiveboardRepository->parseStopAtStation(Object(Irail\\Http\\Requests\\LiveboardV1Request), Object(Irail\\Models\\Station), Array)",
    "#9 /workspace/app/Repositories/Nmbs/NmbsRivLiveboardRepository.php(65): Irail\\Repositories\\Nmbs\\NmbsRivLiveboardRepository->parseNmbsRawData(Object(Irail\\Http\\Requests\\LiveboardV1Request), Object(Irail\\Models\\CachedData))",
    "#10 /workspace/app/Traits/Cache.php(188): Irail\\Repositories\\Nmbs\\NmbsRivLiveboardRepository->Irail\\Repositories\\Nmbs\\{closure}()",
    "#11 /workspace/app/Repositories/Nmbs/NmbsRivLiveboardRepository.php(63): Irail\\Repositories\\Nmbs\\NmbsRivLiveboardRepository->getCacheOrUpdate('|Liveboard|0088...', Object(Closure), 60)",
    "#12 /workspace/app/Repositories/Nmbs/NmbsMergedLiveboardRepository.php(30): Irail\\Repositories\\Nmbs\\NmbsRivLiveboardRepository->getLiveboard(Object(Irail\\Http\\Requests\\LiveboardV1Request))",
    "#13 /workspace/app/Http/Controllers/LiveboardV1Controller.php(31): Irail\\Repositories\\Nmbs\\NmbsMergedLiveboardRepository->getLiveboard(Object(Irail\\Http\\Requests\\LiveboardV1Request))",
    "#14 /workspace/vendor/illuminate/container/BoundMethod.php(36): Irail\\Http\\Controllers\\LiveboardV1Controller->getLiveboardById(Object(Irail\\Http\\Requests\\LiveboardV1Request), '')",
    "#15 /workspace/vendor/illuminate/container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()",
    "#16 /workspace/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))",
    "#17 /workspace/vendor/illuminate/container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))",
    "#18 /workspace/vendor/illuminate/container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)",
    "#19 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(391): Illuminate\\Container\\Container->call(Array, Array)",
    "#20 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(356): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)",
    "#21 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(331): Laravel\\Lumen\\Application->callLumenController(Object(Irail\\Http\\Controllers\\LiveboardV1Controller), 'getLiveboardByI...', Array)",
    "#22 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(284): Laravel\\Lumen\\Application->callControllerAction(Array)",
    "#23 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(269): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)",
    "#24 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(239): Laravel\\Lumen\\Application->handleFoundRoute(Array)",
    "#25 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(174): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)",
    "#26 /workspace/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(48): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#27 /workspace/app/Http/Middleware/RequestLoggingMiddleware.php(29): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#28 /workspace/vendor/illuminate/pipeline/Pipeline.php(183): Irail\\Http\\Middleware\\RequestLoggingMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))",
    "#29 /workspace/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#30 /workspace/app/Http/Middleware/RateLimitMiddleware.php(44): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#31 /workspace/vendor/illuminate/cache/RateLimiter.php(78): Irail\\Http\\Middleware\\RateLimitMiddleware->Irail\\Http\\Middleware\\{closure}()",
    "#32 /workspace/vendor/illuminate/support/Facades/Facade.php(355): Illuminate\\Cache\\RateLimiter->attempt('request_rate|bu...', '35', Object(Closure), '15')",
    "#33 /workspace/app/Http/Middleware/RateLimitMiddleware.php(40): Illuminate\\Support\\Facades\\Facade::__callStatic('attempt', Array)",
    "#34 /workspace/app/Http/Middleware/RateLimitMiddleware.php(23): Irail\\Http\\Middleware\\RateLimitMiddleware->rateLimitedShortTerm(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))",
    "#35 /workspace/vendor/illuminate/pipeline/Pipeline.php(183): Irail\\Http\\Middleware\\RateLimitMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))",
    "#36 /workspace/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#37 /workspace/vendor/illuminate/http/Middleware/TrustProxies.php(39): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#38 /workspace/vendor/illuminate/pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))",
    "#39 /workspace/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#40 /workspace/vendor/illuminate/pipeline/Pipeline.php(119): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
    "#41 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(428): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
    "#42 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(167): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))",
    "#43 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(112): Laravel\\Lumen\\Application->dispatch(NULL)",
    "#44 /workspace/public/index.php(28): Laravel\\Lumen\\Application->run()",
    "#45 {main}"
  ]
}
```

**Comment by Bertware** [comment]
This is a caching issue which seems to occur after a few days, I saved some debugging information and forced a redeploy with clean cache now which should fix the issue

**Comment by Bertware** [comment]
I fixed some error-handling code so the correct underlying issue shows up, something is either wrong in the GTFS or in how iRail handles GTFS:

"'729' occurs twice on the same day at non-connected segments! GTFS trip ids: 88____:007::8896008:8821006:20:923:20241213, 88____:007::8896735:8821006:27:923:20241214"

**Comment by Bertware** [comment]
Fixed now on liveboard-level, the problematic departure will not be shown but all others will show up correctly. Leaving this issue open to figure out the underlying issue, two different trains with the same number running on the same day

**Comment by Bertware** [comment]
> I fixed some error-handling code so the correct underlying issue shows up, something is either wrong in the GTFS or in how iRail handles GTFS:
> 
> "'729' occurs twice on the same day at non-connected segments! GTFS trip ids: 88____:007::8896008:8821006:20:923:20241213, 88____:007::8896735:8821006:27:923:20241214"

Okay so train 729 is defined multiple times, on two different routes, in two different blocks, at the same day.
```
route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,trip_type
375,000208,88____:007::8896008:8821006:20:923:20241213,Anvers-Central,729,,14934,,1
763,000406,88____:007::8896735:8821006:27:923:20241214,Anvers-Central,729,,33537,,1
```

One of the routes originates in France. Since a route contains trips in both directions, the direction of the names in route 763 is not an issue.
```
route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color
375,NMBS/SNCB,IC,Lille Flandres (FR) -- Anvers-Central,,103,,,
763,NMBS/SNCB,IC,Anvers-Central -- Poperinge,,103,,,
```

Calendar dates are similar, but not identical
```
service_id,date,exception_type
000208,20240902,1
000208,20240903,1
000208,20240904,1
000208,20240905,1
000208,20240906,1
000208,20240909,1

000406,20240902,1
000406,20240903,1
000406,20240904,1
000406,20240905,1
000406,20240906,1
000406,20240907,1
```

Searching on the NMBS website returns the Poperinge - Antwerpen Centraal train.
![NMBS Train 729](https://github.com/user-attachments/assets/1756e758-bc74-4602-9267-e83fd14834bb)

The international train has the following stops:
```
88____:007::8896008:8821006:20:923:20241213,07:45:00,07:59:00,8896008_3,8,,0,0,
88____:007::8896008:8821006:20:923:20241213,08:03:00,08:03:00,8896115,9,,1,1,
88____:007::8896008:8821006:20:923:20241213,08:08:00,08:09:00,8896149_2,10,,0,0,
88____:007::8896008:8821006:20:923:20241213,08:16:00,08:16:00,8892106,11,,1,1,
88____:007::8896008:8821006:20:923:20241213,08:19:00,08:19:00,8892080,12,,1,1,
88____:007::8896008:8821006:20:923:20241213,08:24:00,08:27:00,8892007_1,13,,0,0,
88____:007::8896008:8821006:20:923:20241213,08:33:00,08:33:00,8893179,14,,1,1,
88____:007::8896008:8821006:20:923:20241213,08:35:00,08:36:00,8893120_2,15,,0,0,
88____:007::8896008:8821006:20:923:20241213,08:44:00,08:44:00,8894151,16,,1,1,
88____:007::8896008:8821006:20:923:20241213,08:48:00,08:49:00,8894201_2,17,,0,0,
88____:007::8896008:8821006:20:923:20241213,08:54:00,08:54:00,8894425,18,,1,1,
88____:007::8896008:8821006:20:923:20241213,08:55:00,08:55:00,8894433,19,,1,1,
88____:007::8896008:8821006:20:923:20241213,08:58:00,09:00:00,8894508_4,20,,0,0,
88____:007::8896008:8821006:20:923:20241213,09:03:00,09:03:00,8894714,21,,1,1,
88____:007::8896008:8821006:20:923:20241213,09:06:00,09:06:00,8894748,22,,1,1,
88____:007::8896008:8821006:20:923:20241213,09:07:00,09:07:00,8894755,23,,1,1,
88____:007::8896008:8821006:20:923:20241213,09:10:00,09:10:00,8894821,24,,1,1,
88____:007::8896008:8821006:20:923:20241213,09:14:00,09:14:00,8821196,25,,1,1,
88____:007::8896008:8821006:20:923:20241213,09:17:00,09:19:00,8821121_7,26,,0,0,
88____:007::8896008:8821006:20:923:20241213,09:23:00,09:23:00,8821006_2,27,,1,0,
```

It is a part of the national train, seemingly another train being coupled together to this train, as visualised in the poor ASCII drawing below

```
Poperinge ---\
                       > Kortrijk----- Antwerpen
Rijsel ---------/

```

The solution for this is to detect one trip being part of the other, and to pick and return the longest trip.
