### ISSUE TITLE
500 errors on `/vehicle`

### ISSUE THREAD

**Issue by gbougakov** [iRail/iRail#536]
Calling `https://api.irail.be/v1/vehicle?id=IC3630&format=json` returns a 500 error with the following stack trace. 

It is not unique to this vehicle ID, however shifting `date` back a few days before fixes this. Also I noticed that this error appears mostly during the night (right now it's 3AM and I get it for all trains I try to query)

```json
{
	"code": 0,
	"request-id": "9d2b3f65-227f-4962-95ee-ab8e4c21142b",
	"message": "APCUIterator::__construct(): Argument #2 ($format) must be of type int, string given",
	"previous": null,
	"at": "\/workspace\/app\/Traits\/Cache.php:168",
	"stack": [
		"#0 \/workspace\/app\/Traits\/Cache.php(168): APCUIterator->__construct('user', '\/^NMBS|journeyD...')",
		"#1 \/workspace\/app\/Repositories\/Riv\/NmbsRivRawDataRepository.php(135): Irail\\Repositories\\Riv\\NmbsRivRawDataRepository->deleteCachedObjectsByPrefix('NMBS|journeyDet...')",
		"#2 \/workspace\/app\/Repositories\/Nmbs\/NmbsRivVehicleJourneyRepository.php(56): Irail\\Repositories\\Riv\\NmbsRivRawDataRepository->getVehicleJourneyData(Object(Irail\\Http\\Requests\\DatedVehicleJourneyV1Request))",
		"#3 \/workspace\/app\/Http\/Controllers\/DatedVehicleJourneyV1Controller.php(28): Irail\\Repositories\\Nmbs\\NmbsRivVehicleJourneyRepository->getDatedVehicleJourney(Object(Irail\\Http\\Requests\\DatedVehicleJourneyV1Request))",
		"#4 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(36): Irail\\Http\\Controllers\\DatedVehicleJourneyV1Controller->getVehicleById(Object(Irail\\Http\\Requests\\DatedVehicleJourneyV1Request), '')",
		"#5 \/workspace\/vendor\/illuminate\/container\/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()",
		"#6 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))",
		"#7 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))",
		"#8 \/workspace\/vendor\/illuminate\/container\/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)",
		"#9 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(391): Illuminate\\Container\\Container->call(Array, Array)",
		"#10 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(356): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)",
		"#11 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(331): Laravel\\Lumen\\Application->callLumenController(Object(Irail\\Http\\Controllers\\DatedVehicleJourneyV1Controller), 'getVehicleById', Array)",
		"#12 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(284): Laravel\\Lumen\\Application->callControllerAction(Array)",
		"#13 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(269): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)",
		"#14 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(239): Laravel\\Lumen\\Application->handleFoundRoute(Array)",
		"#15 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(174): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)",
		"#16 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(48): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
		"#17 \/workspace\/app\/Http\/Middleware\/RequestLoggingMiddleware.php(29): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
		"#18 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Irail\\Http\\Middleware\\RequestLoggingMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))",
		"#19 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
		"#20 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(44): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
		"#21 \/workspace\/vendor\/illuminate\/cache\/RateLimiter.php(78): Irail\\Http\\Middleware\\RateLimitMiddleware->Irail\\Http\\Middleware\\{closure}()",
		"#22 \/workspace\/vendor\/illuminate\/support\/Facades\/Facade.php(355): Illuminate\\Cache\\RateLimiter->attempt('request_rate|bu...', '35', Object(Closure), '15')",
		"#23 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(40): Illuminate\\Support\\Facades\\Facade::__callStatic('attempt', Array)",
		"#24 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(23): Irail\\Http\\Middleware\\RateLimitMiddleware->rateLimitedShortTerm(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))",
		"#25 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Irail\\Http\\Middleware\\RateLimitMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))",
		"#26 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
		"#27 \/workspace\/vendor\/illuminate\/http\/Middleware\/TrustProxies.php(39): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
		"#28 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))",
		"#29 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
		"#30 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(119): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
		"#31 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(428): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
		"#32 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(167): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))",
		"#33 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(112): Laravel\\Lumen\\Application->dispatch(NULL)",
		"#34 \/workspace\/public\/index.php(28): Laravel\\Lumen\\Application->run()",
		"#35 {main}"
	]
}
```

**Comment by Bertware** [comment]
Thanks for reporting this! 

This is an error in the code, in a method which is rarely called, but may explain some other unstable behaviour at specific times as well.
