### ISSUE TITLE
Production doesn't work anymore. Staging is fine

### ISSUE THREAD

**Issue by koeleboe** [iRail/iRail#538]
@Bertware the production api doesn't work anymore (just an error, 504). The staging however seems to be working fine.

**Comment by Bertware** [comment]
Something goes wrong while updating the GTFS data, staging must be on a cached version which is fine or have a different state in memory. 

 ```
production.ERROR: Undefined array key 20241215 {"exception":"[object] (ErrorException(code: 0): Undefined array key 20241215 at /workspace/app/Repositories/Gtfs/GtfsRepository.php:183)
[irail] [2024-10-14 07:47:05] [stacktrace]
[irail] [2024-10-14 07:47:05] #0 /workspace/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php(47): Laravel\\Lumen\\Application->handleError(2, 'Undefined array...', '/workspace/app/...', 183)
[irail] [2024-10-14 07:47:05] #1 /workspace/app/Repositories/Gtfs/GtfsRepository.php(183): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(2, 'Undefined array...', '/workspace/app/...', 183)
[irail] [2024-10-14 07:47:05] #2 /workspace/app/Repositories/Gtfs/GtfsRepository.php(115): Irail\\Repositories\\Gtfs\\GtfsRepository->getServiceIdsInDateRange(3, 62)
[irail] [2024-10-14 07:47:05] #3 /workspace/app/Repositories/Gtfs/GtfsRepository.php(56): Irail\\Repositories\\Gtfs\\GtfsRepository->readTripsByJourneyNumberAndStartDate()
[irail] [2024-10-14 07:47:05] #4 /workspace/app/Traits/Cache.php(252): Irail\\Repositories\\Gtfs\\GtfsRepository->Irail\\Repositories\\Gtfs\\{closure}()
[irail] [2024-10-14 07:47:05] #5 /workspace/app/Repositories/Gtfs/GtfsRepository.php(55): Irail\\Repositories\\Gtfs\\GtfsRepository->getCacheOrSynchronizedUpdate('trips', Object(Closure), 79526)
[irail] [2024-10-14 07:47:05] #6 /workspace/app/Http/Controllers/StatusController.php(108): Irail\\Repositories\\Gtfs\\GtfsRepository->getTripsByJourneyNumberAndStartDate()
[irail] [2024-10-14 07:47:05] #7 /workspace/app/Http/Controllers/StatusController.php(55): Irail\\Http\\Controllers\\StatusController->warmupCache()
[irail] [2024-10-14 07:47:05] #8 /workspace/vendor/illuminate/container/BoundMethod.php(36): Irail\\Http\\Controllers\\StatusController->maintain()
[irail] [2024-10-14 07:47:05] #9 /workspace/vendor/illuminate/container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
[irail] [2024-10-14 07:47:05] #10 /workspace/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
[irail] [2024-10-14 07:47:05] #11 /workspace/vendor/illuminate/container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))
[irail] [2024-10-14 07:47:05] #12 /workspace/vendor/illuminate/container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)
[irail] [2024-10-14 07:47:05] #13 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(391): Illuminate\\Container\\Container->call(Array, Array)
[irail] [2024-10-14 07:47:05] #14 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(356): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)
[irail] [2024-10-14 07:47:05] #15 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(331): Laravel\\Lumen\\Application->callLumenController(Object(Irail\\Http\\Controllers\\StatusController), 'maintain', Array)
[irail] [2024-10-14 07:47:05] #16 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(284): Laravel\\Lumen\\Application->callControllerAction(Array)
[irail] [2024-10-14 07:47:05] #17 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(269): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)
[irail] [2024-10-14 07:47:05] #18 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(171): Laravel\\Lumen\\Application->handleFoundRoute(Array)
[irail] [2024-10-14 07:47:05] #19 /workspace/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(48): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
[irail] [2024-10-14 07:47:05] #20 /workspace/app/Http/Middleware/RequestLoggingMiddleware.php(29): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
[irail] [2024-10-14 07:47:05] #21 /workspace/vendor/illuminate/pipeline/Pipeline.php(183): Irail\\Http\\Middleware\\RequestLoggingMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))
[irail] [2024-10-14 07:47:05] #22 /workspace/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
[irail] [2024-10-14 07:47:05] #23 /workspace/app/Http/Middleware/RateLimitMiddleware.php(44): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
[irail] [2024-10-14 07:47:05] #24 /workspace/vendor/illuminate/cache/RateLimiter.php(78): Irail\\Http\\Middleware\\RateLimitMiddleware->Irail\\Http\\Middleware\\{closure}()
[irail] [2024-10-14 07:47:05] #25 /workspace/vendor/illuminate/support/Facades/Facade.php(355): Illuminate\\Cache\\RateLimiter->attempt('request_rate|bu...', '35', Object(Closure), '15')
[irail] [2024-10-14 07:47:05] #26 /workspace/app/Http/Middleware/RateLimitMiddleware.php(40): Illuminate\\Support\\Facades\\Facade::__callStatic('attempt', Array)
[irail] [2024-10-14 07:47:05] #27 /workspace/app/Http/Middleware/RateLimitMiddleware.php(23): Irail\\Http\\Middleware\\RateLimitMiddleware->rateLimitedShortTerm(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))
[irail] [2024-10-14 07:47:05] #28 /workspace/vendor/illuminate/pipeline/Pipeline.php(183): Irail\\Http\\Middleware\\RateLimitMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))
[irail] [2024-10-14 07:47:05] #29 /workspace/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
[irail] [2024-10-14 07:47:05] #30 /workspace/vendor/illuminate/http/Middleware/TrustProxies.php(39): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
[irail] [2024-10-14 07:47:05] #31 /workspace/vendor/illuminate/pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))
[irail] [2024-10-14 07:47:05] #32 /workspace/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
[irail] [2024-10-14 07:47:05] #33 /workspace/vendor/illuminate/pipeline/Pipeline.php(119): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
[irail] [2024-10-14 07:47:05] #34 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(428): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
[irail] [2024-10-14 07:47:05] #35 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(167): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
[irail] [2024-10-14 07:47:05] #36 /workspace/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(112): Laravel\\Lumen\\Application->dispatch(NULL)
[irail] [2024-10-14 07:47:05] #37 /workspace/public/index.php(28): Laravel\\Lumen\\Application->run()
[irail] [2024-10-14 07:47:05] #38 {main}
[irail] [2024-10-14 07:47:05] "} 
```

**Comment by Bertware** [comment]
Looked at the code and realized the issue: Production allows queries up to 62 days forward, staging only 14. This caused an issue when production tried to load dates past the GTFS validity date, should be fixed now.

**Comment by xivk** [comment]
Thanks @Bertware for fixing this!
