### ISSUE TITLE
Connections for Lelystad Centrum return error

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#543]
Request: https://api.irail.be/v1/connections/?lang=nl&to=BE.NMBS.008814001&from=BE.NMBS.008400394
Response: 
```xml
<error code="404" requestId="9dbfe5f0-dcc1-4c76-9dd2-27a3238acc50">
Could not match id '008400081' with a station in iRail. Please report this issue at https://github.com/irail/stations/issues/new if you think we should support your query.
</error>
```

Lelystad Centrum was added to stations, though: https://github.com/iRail/stations/commit/cf776bf0ca3f71a9a4c03e589dca2361594fad1e#diff-9802c0ce4fac77febfb0e2cf8241f9c6fa73601b0e87abd9ead64683847061a5R377

**Comment by jncn** [comment]
The NMBS app displays it correctly:

![IMG_8928B8C44252-1](https://github.com/user-attachments/assets/92fb0751-f3fd-49df-92f5-b3595e3ea799)

**Comment by Bertware** [comment]
Almere buiten is missing, will fix

**Comment by jncn** [comment]
Thanks Bert, but it's generating a different error now. (Maybe I'm too fast, if so, please ignore this comment.)

Request: https://api.irail.be/v1/connections/?lang=en&to=BE.NMBS.008400394&from=BE.NMBS.008814001

Response:
```JSON
{"code":0,"request-id":"9dcc1b12-c938-45c6-85de-1d670f99dfd1","message":"Call to a member function getLocalizedStationName() on null","previous":null,"at":"\/workspace\/app\/Http\/Responses\/v1\/JourneyPlanningV1Converter.php:68","stack":["#0 \/workspace\/app\/Http\/Responses\/v1\/JourneyPlanningV1Converter.php(68): Irail\\Http\\Responses\\v1\\JourneyPlanningV1Converter::convertDirection(Object(Irail\\Models\\DepartureOrArrival))","#1 \/workspace\/app\/Http\/Responses\/v1\/JourneyPlanningV1Converter.php(38): Irail\\Http\\Responses\\v1\\JourneyPlanningV1Converter::convertDeparture(Object(Irail\\Models\\DepartureOrArrival), Object(Irail\\Models\\JourneyLeg))","#2 \/workspace\/app\/Http\/Responses\/v1\/JourneyPlanningV1Converter.php(31): Irail\\Http\\Responses\\v1\\JourneyPlanningV1Converter::convertJourneyPlan(Object(Irail\\Models\\Journey))","#3 [internal function]: Irail\\Http\\Responses\\v1\\JourneyPlanningV1Converter::Irail\\Http\\Responses\\v1\\{closure}(Object(Irail\\Models\\Journey))","#4 \/workspace\/app\/Http\/Responses\/v1\/JourneyPlanningV1Converter.php(31): array_map(Object(Closure), Array)","#5 \/workspace\/app\/Http\/Controllers\/JourneyPlanningV1Controller.php(37): Irail\\Http\\Responses\\v1\\JourneyPlanningV1Converter::convert(Object(Irail\\Http\\Requests\\JourneyPlanningV1RequestImpl), Object(Irail\\Models\\Result\\JourneyPlanningSearchResult))","#6 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(36): Irail\\Http\\Controllers\\JourneyPlanningV1Controller->getJourneyPlanning(Object(Irail\\Http\\Requests\\JourneyPlanningV1RequestImpl), '')","#7 \/workspace\/vendor\/illuminate\/container\/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()","#8 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))","#9 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))","#10 \/workspace\/vendor\/illuminate\/container\/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)","#11 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(391): Illuminate\\Container\\Container->call(Array, Array)","#12 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(356): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)","#13 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(331): Laravel\\Lumen\\Application->callLumenController(Object(Irail\\Http\\Controllers\\JourneyPlanningV1Controller), 'getJourneyPlann...', Array)","#14 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(284): Laravel\\Lumen\\Application->callControllerAction(Array)","#15 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(269): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)","#16 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(239): Laravel\\Lumen\\Application->handleFoundRoute(Array)","#17 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(174): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)","#18 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(48): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#19 \/workspace\/app\/Http\/Middleware\/RequestLoggingMiddleware.php(29): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#20 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Irail\\Http\\Middleware\\RequestLoggingMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#21 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#22 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(51): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#23 \/workspace\/vendor\/illuminate\/cache\/RateLimiter.php(78): Irail\\Http\\Middleware\\RateLimitMiddleware->Irail\\Http\\Middleware\\{closure}()","#24 \/workspace\/vendor\/illuminate\/support\/Facades\/Facade.php(355): Illuminate\\Cache\\RateLimiter->attempt('request_rate|bu...', '30', Object(Closure), '15')","#25 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(47): Illuminate\\Support\\Facades\\Facade::__callStatic('attempt', Array)","#26 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(24): Irail\\Http\\Middleware\\RateLimitMiddleware->rateLimitedShortTerm(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#27 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Irail\\Http\\Middleware\\RateLimitMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#28 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#29 \/workspace\/vendor\/illuminate\/http\/Middleware\/TrustProxies.php(39): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#30 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#31 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#32 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(119): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#33 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(428): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#34 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(167): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#35 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(112): Laravel\\Lumen\\Application->dispatch(NULL)","#36 \/workspace\/public\/index.php(28): Laravel\\Lumen\\Application->run()","#37 {main}"]}
```

**Comment by Bertware** [comment]
Amsterdam South couldn't be found based on it's name, added some fallback code and the English name in the stations dataset now,

**Comment by jncn** [comment]
Thanks!
