### ISSUE TITLE
Error on /composition

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#546]
All compositions give errors currently.

Request: https://api.irail.be/v1/composition/?lang=nl&id=BE.NMBS.IC3614

Response:
```JSON
{"code":"25006","request-id":"9dcd300d-da79-4708-a8c3-c744ba2d66c4","message":"SQLSTATE[25006]: Read only sql transaction: 7 ERROR:  cannot execute DELETE in a read-only transaction (Connection: pgsql, SQL: delete from \"composition_history\" where \"id\" = 2165724)","previous":{"errorInfo":["25006",7,"ERROR:  cannot execute DELETE in a read-only transaction"]},"at":"\/workspace\/app\/Database\/HistoricCompositionDao.php:275","stack":["#0 \/workspace\/vendor\/illuminate\/database\/Connection.php(783): Illuminate\\Database\\Connection->runQueryCallback('delete from \"co...', Array, Object(Closure))","#1 \/workspace\/vendor\/illuminate\/database\/Connection.php(600): Illuminate\\Database\\Connection->run('delete from \"co...', Array, Object(Closure))","#2 \/workspace\/vendor\/illuminate\/database\/Connection.php(564): Illuminate\\Database\\Connection->affectingStatement('delete from \"co...', Array)","#3 \/workspace\/vendor\/illuminate\/database\/Query\/Builder.php(3796): Illuminate\\Database\\Connection->delete('delete from \"co...', Array)","#4 \/workspace\/vendor\/illuminate\/database\/Eloquent\/Builder.php(1273): Illuminate\\Database\\Query\\Builder->delete()","#5 \/workspace\/vendor\/illuminate\/database\/Eloquent\/Model.php(1463): Illuminate\\Database\\Eloquent\\Builder->delete()","#6 \/workspace\/vendor\/illuminate\/database\/Eloquent\/Model.php(1408): Illuminate\\Database\\Eloquent\\Model->performDeleteOnModel()","#7 \/workspace\/vendor\/illuminate\/database\/Eloquent\/Model.php(1369): Illuminate\\Database\\Eloquent\\Model->delete()","#8 \/workspace\/app\/Database\/HistoricCompositionDao.php(275): Illuminate\\Database\\Eloquent\\Model::destroy(Array)","#9 \/workspace\/app\/Database\/HistoricCompositionDao.php(160): Irail\\Database\\HistoricCompositionDao->deleteCompositionHistory(2165724)","#10 \/workspace\/app\/Database\/HistoricCompositionDao.php(141): Irail\\Database\\HistoricCompositionDao->recordComposition(Object(Irail\\Models\\VehicleComposition\\TrainComposition))","#11 \/workspace\/app\/Http\/Controllers\/CompositionV1Controller.php(49): Irail\\Database\\HistoricCompositionDao->recordComposition(Object(Irail\\Models\\Result\\VehicleCompositionSearchResult))","#12 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(36): Irail\\Http\\Controllers\\CompositionV1Controller->getVehicleComposition(Object(Irail\\Http\\Requests\\VehicleCompositionV1Request), '')","#13 \/workspace\/vendor\/illuminate\/container\/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()","#14 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))","#15 \/workspace\/vendor\/illuminate\/container\/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))","#16 \/workspace\/vendor\/illuminate\/container\/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)","#17 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(391): Illuminate\\Container\\Container->call(Array, Array)","#18 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(356): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)","#19 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(331): Laravel\\Lumen\\Application->callLumenController(Object(Irail\\Http\\Controllers\\CompositionV1Controller), 'getVehiclecompo...', Array)","#20 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(284): Laravel\\Lumen\\Application->callControllerAction(Array)","#21 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(269): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)","#22 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(239): Laravel\\Lumen\\Application->handleFoundRoute(Array)","#23 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(174): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)","#24 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(48): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#25 \/workspace\/app\/Http\/Middleware\/RequestLoggingMiddleware.php(29): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#26 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Irail\\Http\\Middleware\\RequestLoggingMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#27 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#28 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(51): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#29 \/workspace\/vendor\/illuminate\/cache\/RateLimiter.php(78): Irail\\Http\\Middleware\\RateLimitMiddleware->Irail\\Http\\Middleware\\{closure}()","#30 \/workspace\/vendor\/illuminate\/support\/Facades\/Facade.php(355): Illuminate\\Cache\\RateLimiter->attempt('request_rate|bu...', '30', Object(Closure), '15')","#31 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(47): Illuminate\\Support\\Facades\\Facade::__callStatic('attempt', Array)","#32 \/workspace\/app\/Http\/Middleware\/RateLimitMiddleware.php(24): Irail\\Http\\Middleware\\RateLimitMiddleware->rateLimitedShortTerm(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#33 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Irail\\Http\\Middleware\\RateLimitMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#34 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#35 \/workspace\/vendor\/illuminate\/http\/Middleware\/TrustProxies.php(39): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#36 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))","#37 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#38 \/workspace\/vendor\/illuminate\/pipeline\/Pipeline.php(119): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))","#39 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(428): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#40 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(167): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#41 \/workspace\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(112): Laravel\\Lumen\\Application->dispatch(NULL)","#42 \/workspace\/public\/index.php(28): Laravel\\Lumen\\Application->run()","#43 {main}"]}
```

**Comment by Bertware** [comment]
This is a database issue I just encountered while cleaning up some old data, should be fixed soon when old data which already has been exported has been removed
